%global commit c74e8e026445540143e90bd027fb074eec698ac6
%global shortcommit %(c=%{commit}; echo ${c:0:7})
%global repo_name linux-kstat

Name:           perl-Sun-Solaris-Kstat
Version:        0.01
Release:        1%{?dist}
Summary:        Linux-compatible kstat interface
License:        GPLv2+
Group:          Development/Libraries
URL:            https://github.com/zfsonlinux/%{repo_name}
Source0:        https://github.com/zfsonlinux/%{repo_name}/archive/%{commit}/%{name}-%{version}-%{shortcommit}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module provides an interface for the Linux ZFS kernel module that
is compatible with the Sun::Solaris::Kstat Perl module found on
Solaris systems.

%prep
%setup -qn %{repo_name}-%{commit}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jul 23 2013 Trey Dockendorf <treydock@gmail.com> 0.01-1
- Specfile autogenerated by cpanspec 1.78.
